FROM alpine:edge

ARG USER=jess
ENV HOME /home/$USER

RUN echo "https://dl-cdn.alpinelinux.org/alpine/edge/testing" >> /etc/apk/repositories \
	&& apk add --update sudo openssh git yadm powershell carapace hyfetch fastfetch

# add new user
RUN adduser -D $USER \
        && echo "$USER ALL=(ALL) NOPASSWD: ALL" > /etc/sudoers.d/$USER \
        && chmod 0440 /etc/sudoers.d/$USER

USER $USER
WORKDIR $HOME

# files in /home/$USER to be owned by $USER
# docker has --chown flag for COPY, but it does not expand ENV so we fallback to:
# COPY src src
# RUN sudo chown -R $USER:$USER $HOME

RUN yadm clone git@github.com:FracturedCode/dotfiles.git \
	&& yadm bootstrap

ENTRYPOINT [ "/usr/bin/pwsh" ]