#!/bin/sh

confirm_continue() {
	local prompt="${1:-Continue}"
	echo -n "$prompt (Y/n): "
	read answer
	if [ "${answer,,}" != "y" ]; then
		exit 1
	fi
}

# This hides files we don't want visible in $HOME
cd "$HOME"
yadm submodule update --recursive --init
yadm gitconfig core.sparseCheckout true
yadm sparse-checkout set --no-cone '/*' '!README.md' '!LICENSE' '!.gitmodules'

confirm_continue "This is a destructive operation, continue?"

rm $HOME/.nanorc
rm $HOME/.gitconfig
rm $HOME/.gnupg

which systemctl
if [ $? -eq 0 ]; then
	for file in $HOME/.config/systemd/user/*; do
		if [ -f "$file" ]; then
			echo "Processing user service: $(basename '$file')"
			systemctl --user enable $file
			systemctl --user daemon-reload
			systemctl --user start $file
		fi
	done
fi