#!/bin/sh

# This hides files we don't want visible in $HOME, but want in the repo nontheless.
cd "$HOME"
yadm submodule update --recursive --init
yadm gitconfig core.sparseCheckout true
yadm sparse-checkout set --no-cone '/*' '!README.md' '!LICENSE' '!.gitmodules' '!Dockerfile' '!prompt-*.png'

# Add some of the XDG directories
mkdir -p $HOME/.config $HOME/.local/state $HOME/.local/share

# This removes clutter from $HOME in order to configure in a more XDG-compliant way

rm $HOME/.nanorc
rm $HOME/.gitconfig
rmdir $HOME/.gnupg

# This enables the user systemctl services
which systemctl
if [ $? -eq 0 ]; then
	for file in $HOME/.config/systemd/user/*; do
		if [ -f "$file" ]; then
			echo "Processing user service: $(basename '$file')"
			systemctl --user enable $file
			systemctl --user daemon-reload
			systemctl --user start $file
		fi
	done
fi